package com.zerolooksgood.demo.EmployeeRepositoryDemo.entity;


import jakarta.persistence.*;

//This is the object that we will use to represent the rows from the database
@Entity //Marks this class as an entity (2)
@Table(name="employees") //Links this class to the employees table in the database
public class Employee {

    @Id //Marks this variable as the identifying variable
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Says that this variable is an autogenerated one
    @Column(name="id") //Links this variable to the chosen column (in this case "id")
    private int id;

    @Column(name="first_name") //It is important to make sure that name="{name}" matches with the column in your database
    private String firstName;

    @Column(name="last_name")
    private String lastName;

    @Column(name="email")
    private String email;

    //JPA-Repository will automatically utilize the following constructors and getters-and-setters

    public Employee() {} //This class NEEDS an empty constructor to work properly with the repository
    public Employee(String firstName, String lastName, String email) { //This constructor does not include the variable "id" because this variable has it's value generated by the database
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override //Overides the standard toString function that comes with the entity definition
    public String toString() { //Simply converts all the data of an object to a single string to be read
        return "Employee{" +
                "id=" + id +
                ", firstName='" + firstName + "'" +
                ", lastName='" + lastName + "'" +
                ", email='" + email + "'" +
                "}";

    }
}
